services:
  web:
    extends:
      file: docker-compose.core.yaml
      service: web

  app:
    extends:
      file: docker-compose.core.yaml
      service: app

  cron:
    extends:
      file: docker-compose.core.yaml
      service: cron
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  db:
    extends:
      file: docker-compose.extra.yaml
      service: db

  cache:
    extends:
      file: docker-compose.extra.yaml
      service: cache

  init:
    extends:
      file: docker-compose.extra.yaml
      service: init

  cf:
    restart: always
    image: cloudflare/cloudflared
    env_file:
      - ./.env
    command: tunnel --no-autoupdate run --token $CFD_TOKEN

volumes:
  public:
  storage:
  socket:
